### PR TITLE
Update of French translation

### PR DESCRIPTION
**Pull request by vinix38**
Small changes to keep the translation up to date :)

### CODE REVIEW

**Comment by yalov** [comment]
thanks

**Comment by yalov** [comment]
if you have time, check please https://github.com/yalov/CommNetAntennasExtension and https://github.com/yalov/CommNetAntennasConsumptor

**Comment by yalov** [comment]
@vinix38 

I have added 2 lines, probably it will be quicker to translate there in the comments:
```
#CAE_PAW_OtherVesselRating = Other Vessel Rating
#CAE_PAW_Distance = Distance: <<1>> 
```

**Comment by vinix38** [comment]
There you go 🙂

#CAE_PAW_OtherVesselRating = Classe de l'Autre Vaisseau
#CAE_PAW_Distance = Distance : <<1>>

**Pull request merged**
